### ISSUE TITLE
Update for Nextcloud 25

### ISSUE THREAD

**Issue by dan91** [nextcloud/jitsi#14]
Hi! I noticed that this integration is not comptabile with NC25. Seems like the layout and graphics are messed up when "enforcing" the update. Any chance there will be an update? Thanks!

**Comment by g-vidal** [comment]
:+1:  I second many thanks if you can do the job

**Comment by weeman1337** [comment]
Working on this…

**Comment by g-vidal** [comment]
Many thanks @weeman1337

**Comment by weeman1337** [comment]
Nextcloud Jitsi 0.16 now supports Nextcloud 25 :partying_face: Please update the app version.

If you find any issues please report them in the tracker here.

**Comment by g-vidal** [comment]
Thanks for the efforts @weeman1337 . Unfortunately it seems that there is a remaining problem with composer.
Here is the message that appears when nextcloud is locked : 
`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0".`
I disabled jitsi  and v25.0 was able to run properly but when I tried to install the app from inside it failed.

Can I help in any way ?

**Comment by weeman1337** [comment]
@g-vidal there should be an update (0.16.1) supporting PHP 7.4 +

**Comment by g-vidal** [comment]
Thanks again @weeman1337 , The install works perfectly and after some deep hunting I found residual bugs mixing up php7.4 and 8.0 I think everything is clean now and I will check `jitsi app` tomorrow with colleagues in more decent time...

The update to `0.16.1` worked smoothly and it might be usefull for users working with `stock bullseye PHP`
