### ISSUE TITLE
Vertical scroll missing with long list of jitsi rooms on Nextcloud 25

### ISSUE THREAD

**Issue by daniele-barresi** [nextcloud/jitsi#19]
Hello,
I'm using Nextcloud snap package on Ubuntu server.
Last night I received the automatic update to Nextcloud 25.0.2.
The Jitsi integration is updated to the latest version available today: 0.16.1.

The Jitsi integration lists rooms, but with a large number of rooms the list does not scroll vertically. As a consequence, some rooms that where created previously are not available/visible any more.

Thanks for this plugin!

**Comment by weeman1337** [comment]
Hey @daniele-barresi . Thanks for reporting the issue. I have just released 0.16.2. This version should fix the issue.

**Comment by daniele-barresi** [comment]
Hello @weeman1337, 
I confirm the issue is resolved with release 0.16.2.

Thank you again for your time and effort!
Cheers
