### ISSUE TITLE
Nextcloud header overlaps with jitsi interface

### ISSUE THREAD

**Issue by kerel-fs** [nextcloud/jitsi#20]
:lady_beetle: **Problem**

The header / banner / navigation bar at the top of the viewport overlaps the jitsi conference-container. Thus interface elements at the top of the jitsi app can't be accessed, e.g. the button to close the chat. This is especially unfortunate as a click on this "close chat" button will open a different nextcloud app instead (in the example screenshot it's the Contacts app), thus leaving the jitsi room.
Example screenshot of the problem:
![nextcloud-jitsi-issue](https://user-images.githubusercontent.com/10089607/212042070-3e7caee1-80d1-4ebf-9b3c-a98b2caa7501.png)

Please let me know if additional debug information is needed!
 
:bulb: **Possible solution**

Use the remaining space below the header for the jitsi app instead of using the full viewport. Unfortunately my knowledge of nextcloud wasn't enough to add/modify the respective CSS rules yet.

**Comment by weeman1337** [comment]
Thanks for reporting the issue @kerel-fs . Can you provide the following information:
- Your browser + version
- Your Nextcloud version
- Version of the Jitsi app

**Comment by kerel-fs** [comment]
Browsers:
- Mozilla Firefox for Arch Linux, version 108.0.1 (64-bit) 
- Chromium Version 108.0.5359.124 (Official Build) Arch Linux (64-bit)

Nextcloud version: 25.0.0
Jitsi Integration version: 0.15.0

**Comment by weeman1337** [comment]
[Jitsi app 0.15 doesn't support Nextcloud 25](https://apps.nextcloud.com/apps/jitsi)

Can you update to the latest version and try again?

**Comment by kerel-fs** [comment]
no, as I am not the server admin.
I'm fine with this issue getting closed. If it is reproducible with a supported version I would re-open it.

Thanks for your support!

**Comment by kerel-fs** [comment]
Issue fixed by update to latest Jitsi Integration (probably 16.2). The Nextcloud header / navigation bar is not displayed anymore while in a meeting.
