### ISSUE TITLE
Server is still falling back to using https://meet.jit.si/

### ISSUE THREAD

**Issue by jcalfee** [nextcloud/jitsi#28]
Recently the Jitsi / Next plugin starting switching to meet.jit.si during conferences after reporting a week connection.  I would like it to fail rather than use a 3rd party server.  In the App's administrative setting though, it is unclear to me why this is a server but it still requires a "Server URL" .. Shouldn't it point to itself? 

![image](https://github.com/nextcloud/jitsi/assets/204121/2f68f4ef-ebb0-461f-a628-23617b506cd4)

**Comment by weeman1337** [comment]
Hello @jcalfee :wave:

Server URL in the settings is the Jitsi instance the plugin is using.
If it says `https://meet.jit.si/` , then it always uses `meet.jit.si`.
It should never automatically reset the setting to `meet.jti.si`.

Can you confirm, that you have something different than `meet.jit.si` in the settings and it is still connecting that instance?

**Comment by jcalfee** [comment]
Ok, I guess I was assuming the plugin was a Jitsi server.  This makes sense, although it is open source it is pretty complex so it makes more sense that I would need my own with the JSON Web Token.  Ok, thank you.
