### ISSUE TITLE
Nextcloud 29

### ISSUE THREAD

**Issue by trivialkettle** [nextcloud/jitsi#37]
The plugin version 0.18.0 states
> This app cannot be installed because the following dependencies are not fulfilled:
>    Server version 28 or lower is required. 

Though it still seems to work.

**Comment by gibelium** [comment]
Would be nice to have the app updated for NC 29

**Comment by stepcellwolf** [comment]
+1

**Comment by mmmrein** [comment]
+1

**Comment by ozgurkazancci** [comment]
+1

**Comment by weeman1337** [comment]
I have released v 0.19 of the app with support for Nextcloud 29 and 30. It should be available trough the Nextcloud app store soon.

**Comment by mmmrein** [comment]
> I have released v 0.19 of the app with support for Nextcloud 29 and 30. It should be available trough the Nextcloud app store soon.

Thank`s a lot, very much appreciated!
