### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by errotu** [nextcloud/jitsi#7]
Thanks a lot for offering this app!

I tried to install it in the app store, but it fails with the following error:

>  Server error: `GET https://pubcode.weimann.digital/downloads/projects/nextcloud-jitsi/builds/48/artifacts/nextcloud-jitsi.tar.gz` resulted in a `500 Server Error` response: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 500 Internal server error (truncated...)

**Comment by weeman1337** [comment]
Thanks for reporting @errotu . I will work on a fix asap.

**Comment by weeman1337** [comment]
Paths have changed. @errotu can you test if it works now?

**Comment by errotu** [comment]
Works! Thanks a lot for the quick fix!

**Comment by weeman1337** [comment]
Thanks for verifying :slightly_smiling_face:
